name: Build & Distribute APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Upload to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Decrypt keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > composeApp/keystore.jks

      - name: Build release APK
        run: |
          ./gradlew assembleRelease \
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute composeApp/build/outputs/apk/release/composeApp-release.apk \
          --app 1:798182551706:android:1d8bc022b5bd717b25ef23 \
          --testers shashankhr018@gmail.com \
          --token ${{ secrets.FIREBASE_TOKEN }}
