name: Build & Distribute APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Upload to Firebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decrypt keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant Gradle permissions
        run: chmod +x ./gradlew

      - name: Build release APK
        run: |
          ./gradlew assembleRelease \
          -Pandroid.injected.signing.store.file=keystore.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Upload to Firebase App Distribution
        run: |
          firebase appdistribution:distribute app/build/outputs/apk/release/app-release.apk \
          --app 1:798182551706:android:1d8bc022b5bd717b25ef23 \
          --groups shashankhr018@gmail.com \
          --token ${{ secrets.FIREBASE_TOKEN }}
